name: Ktlint

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  ktlint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: "Install ktlint"
        uses: nbadal/action-ktlint-setup@v1
        with:
          ktlint_version: '0.50.0'
      - run: ktlint
        shell: bash
