name: Publish

on:
  workflow_run:
    workflows: [Build and test]
    types: [completed]
    branches: [main]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin

      - uses: gradle/actions/setup-gradle@v4

      - name: Publish artifact
        run: ./gradlew publish
        env:
          ORG_GRADLE_PROJECT_githubPassword: ${{ secrets.GITHUB_TOKEN }}
